---

- name: Add celery user
  user:
    name: celery
    state: present

- name: Ensure installation directories
  file:
    path: "{{ item }}"
    owner: celery
    group: celery
    mode: 0770
    state: directory
    recurse: yes
  with_items:
    - "{{ datacatalog_islandoraq_dir }}/ssl/client"
    - "{{ datacatalog_islandoraq_dir }}/ssl/testca"

- name: copy datacatalog pubkeys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: celery
    group: celery
    mode: 0644
  with_items:
    - src: cert.pem
      dest: "{{ datacatalog_islandoraq_dir }}/ssl/client/cert.pem"
    - src: cacert.pem
      dest: "{{ datacatalog_islandoraq_dir }}/ssl/testca/cacert.pem"

- name: copy deployment keys
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: celery
    group: celery
    mode: 0600
  no_log: true
  with_items:
    - content: "{{ datacatalog_islandoraq_rabbit_key_content }}"
      dest: "{{ datacatalog_islandoraq_dir }}/ssl/client/key.pem"
    - content: "{{ datacatalog_islandoraq_mongo_key_content }}"
      dest: "{{ datacatalog_islandoraq_dir }}/ssl/client/mongodb.pem"

- name: Install oulib-islandoraq service
  template:
    src: oulib-islandoraq.service.j2
    dest: /lib/systemd/system/oulib-islandoraq.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
