---
# tasks file for celery-workerq
- include: mamba.yml
  become: true

- include: config-workerq.yml
  become: true

- include: config-adminq.yml
  become: true

- include: yum.yml
  become: true

- include: pip-workerq.yml
  become: true

- include: pip-adminq.yml
  become: true
