---

- include: config-workerq.yml
  become: true

- include: config-adminq.yml
  become: true

  #- include: yum.yml
  #  become: true

- include: mamba-workerq.yml
  become: true

- include: mamba-adminq.yml
  become: true
