---

- name: Pip dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ celery_workerq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
  with_items:
  - name: celery
    version: 3.1.22
  - name: pymongo
    version: 3.2.1

- name: Ensure virtual environment permissions
  file:
    path: "{{ celery_workerq_dir }}/virtpy"
    owner: "{{ celery_workerq_user }}"
    group: "{{ celery_workerq_user }}"
    recurse: yes
