---

- name: Remove previous virtualenv
  file: 
    path: "{{ celery_workerq_dir }}/virtpy"
    state: absent

- name: Pip dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ celery_workerq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
    virtualenv_python: "{{ virtualenv_python_version | default('python') }}" 
  with_items:
  - name: celery
    version: "{{ celery_workerq_celery_version }}"
  - name: pymongo
    version: "{{ celery_workerq_pymongo_version }}"

- name: Ensure virtual environment permissions
  file:
    path: "{{ celery_workerq_dir }}/virtpy"
    owner: "{{ celery_workerq_user }}"
    group: "{{ celery_workerq_user }}"
    recurse: yes

- name: Ensure cyberCommons is listed to /etc/hosts
  lineinfile:
    destfile: /etc/hosts
    line: "{{ celery_etc_host_entry }}"
