---

- name: Remove previous virtualenv
  file:
    path: "{{ celery_adminq_dir }}/virtpy"
    state: absent

- name: Pip dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ celery_adminq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
    virtualenv_python: "{{ virtualenv_python_version | default('python') }}"
  with_items:
  - name: celery
    version: "{{ celery_adminq_celery_version }}" 
  - name: pymongo
    version: "{{ celery_adminq_pymongo_version }}"

- name: celery adminq module
  pip:
    name: "git+{{ celery_adminq_git }}"
    virtualenv: "{{ celery_adminq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
    editable: false
  notify:
    - restart oulib-celery-adminq.service

- name: Ensure virtual environment permissions
  file:
    path: "{{ celery_adminq_dir }}/virtpy"
    owner: "{{ celery_adminq_user }}"
    group: "{{ celery_adminq_user }}"
    recurse: yes
