---

- name: Pip dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ celery_workerq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
  with_items:
  - name: celery
    version: 3.1.22
  - name: pymongo
    version: 3.2.1

- name: Islandoraq
  pip:
    name: "{{ item.name }}"
    virtualenv: "{{ celery_workerq_dir }}/virtpy"
    virtualenv_site_packages: yes
    state: present
    editable: false
  with_items:
  - name: git+https://github.com/oulib-celery/workerq
  notify:
    - restart oulib-celery-workerq.service
