---

- name: Packages for yum.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - gcc
      - gcc-c++
      - "{{ python_pkg }}"
      - "{{ python_devel_pkg }}"
      - "{{ python_virtualenv_pkg }}"
      - libcurl-devel
      - libffi-devel
      - openssl-devel
