---

- name: Packages for yum.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - python-devel
    - python-virtualenv
    - libcurl-devel
    - libffi-devel
    - openssl-devel
