---
# handlers file for celery-workerq
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: start oulib-celery-workerq-installer.service
  service:
    name: oulib-celery-workerq
    state: started
    enabled: yes
  become: true

- name: wait for oulib-celery-workerq-installer
  wait_for:
    path: {{ celery_workerq_dir }}/virtpy/lib/python2.7/site-packages/{{ celery_workerq_imports }}
    state: present
  become: true

- name: restart oulib-celery-workerq.service
  service:
    name: oulib-celery-workerq
    state: restarted
    enabled: yes
  become: true

- name: restart oulib-celery-adminq.service
  service:
    name: oulib-celery-adminq
    state: restarted
    enabled: yes
  become: true
