---
# handlers file for celery-workerq
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart oulib-celery-workerq.service
  service:
    name: oulib-celery-workerq
    state: restarted
    enabled: yes
  become: true

- name: restart oulib-celery-adminq.service
  service:
    name: oulib-celery-adminq
    state: restarted
    enabled: yes
  become: true
